name: amork
description: Food Delivery Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.6.0
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  uuid: ^4.3.3
  image_picker: ^1.2.1
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/